# Generated by Django 4.2.6 on 2023-12-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type_of_work',
        ),
    ]
