# Generated by Django 4.2.6 on 2023-12-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_remove_user_type_of_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
