# Generated by Django 4.2.6 on 2024-02-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='session_id',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
