# Generated by Django 4.2.6 on 2024-03-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_premium_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='customer_id',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premium',
            name='session_id',
            field=models.BinaryField(),
        ),
    ]
